#!/bin/sh

#  Script is runing from Jenkins.
#
#  Created by Alexander Tyschenko on 29/01/12.
#  Copyright 2012 Stanfy. All rights reserved.

# determining from which directory script is executed
DIR="$( cd -P "$( dirname "$0" )" && pwd )"

# going to cintegration / bin directory
cd ${DIR}

if [ `echo ${JOB_NAME} | grep '\-auto'` ]
then
  INIT_TYPE='auto'
else
  INIT_TYPE='manual'
# if [ $# -gt 0 ]
# then
#   INIT_TYPE=$1
#   export INIT_TYPE
# else
#  INIT_TYPE=''
# fi
fi

export INIT_TYPE

if [ "$BuildDev" == "true" ]; then
  ./build dev 
fi
if [ "$BuildClient" == "true" ]; then
  ./build client
fi
