#!/bin/sh

#  Script is runing from Jenkins.
#
#  Created by Alexander Tyschenko on 29/01/12.
#  Copyright 2012 Stanfy. All rights reserved.

# determining from which directory script is executed
DIR="$( cd -P "$( dirname "$0" )" && pwd )"

# clean DerivedData and Workspace


if [ "_$CleanProject" = "_true" ]
then
  echo
  echo "-- PROJECT CLEANING --"
  echo
  DERIVEDDATA_DIR=$(grep -oE "/usr/bin/touch -c .*\.app" "$DIR/../output/build.log"  2> /dev/null| head -n1 | sed -e 's/.*\ \(.*\)\/Build\/.*/\1/')
  if [ -d "$DERIVEDDATA_DIR" ]
  then
    rm -rf "$DERIVEDDATA_DIR"
    echo "[DEBUG] DerivedData $DERIVEDDATA_DIR is removed"
  else
    echo "[ERROR] DerivedData dir $DERIVEDDATA_DIR is not found"
    echo
    echo "[INFO] First build project and then you may clean it"
    echo
    exit 1
  fi
  
  echo
  find . -exec rm -rf {} \; 2> /dev/null
  echo "[DEBUG] Workspace $WORKSPACE is removed"
  echo
  exit
  
fi

# install pods

podfile=$(find . -name Podfile -maxdepth 2 )

podfile_dir=$(echo "$podfile" | xargs dirname)

mod_time=$(stat -f %m "$podfile")

now_time=$(date +%s)

let "diff_time = $now_time - $mod_time" 

if [ $diff_time -lt 60 ]
then 
	echo 
	echo "-- PODS INSTALLING --"
	cd "$podfile_dir"
	pod install --no-color
	echo
fi


# going to cintegration / bin directory
cd "${DIR}"

if [ $# -gt 0 ]
then
  INIT_TYPE=$1
  export INIT_TYPE
fi



if [ "$BuildDev" == "true" ]; then
  ./build dev 
  if [ "$?" -ne "0" ]; then
  exit 1
fi
fi

if [ "$BuildClient" == "true" ]; then
  ./build client
  if [ "$?" -ne "0" ]; then
  exit 1
fi
fi
